name: job_interview_practice
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.2
  firebase_core: ^0.5.1
  shared_preferences: ^0.5.12+4
  dartz:
  equatable:
  flutter_bloc:
  get_it: ^5.0.1
  cupertino_icons: ^1.0.0
  camera: ^0.5.8+11
  path_provider: ^1.6.24
  hive: ^1.4.4+1
  intl: ^0.16.1
  video_player: ^1.0.1
  chewie: ^0.12.0
  cached_network_image: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - images/
